name = "worker-rust"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "MRL_DB"
database_id = "1b3d0b4e-035a-4fc2-8a01-080702ba01bf"

[triggers]
# - Every 4 hours
crons = [ "* 0/4 * * *"]

[env.dev.triggers]
# - At every minute
#crons = ["*/1 * * * *"]
crons = ["* 0/1 * * *"]